### ISSUE TITLE
login error but working

### ISSUE THREAD

**Issue by platini76** [szlaskidaniel/homebridge-risco-alarm#10]
node:30974) UnhandledPromiseRejectionWarning: Error: Unhandled "error" event. (error)
    at pollingtoevent.emit (events.js:186:19)
    at done (/usr/lib/node_modules/homebridge-risco-alarm/node_modules/polling-to-event/index.js:33:20)
    at /usr/lib/node_modules/homebridge-risco-alarm/app.js:74:17
    at /usr/lib/node_modules/homebridge-risco-alarm/app.js:281:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:30974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
homebridge : TTY=pts/0 ; PWD=/var/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
[2018-10-10 03:15:50] [RiscoAlarm] Body.error = 3 , relogin.
[2018-10-10 03:15:50] [RiscoAlarm] Sesion expired, relogin...
[2018-10-10 03:15:50] [RiscoAlarm] login [step1] to RiscoCloud first stage...
keep sid:fprt7mlj
[2018-10-10 03:15:51] [RiscoAlarm] Got Cookie, save it
[2018-10-10 03:15:51] [RiscoAlarm] login [step2] > err: null
[2018-10-10 03:15:51] [RiscoAlarm] Login failed
(node:30974) UnhandledPromiseRejectionWarning: Error: Unhandled "error" event. (error)
    at pollingtoevent.emit (events.js:186:19)
    at done (/usr/lib/node_modules/homebridge-risco-alarm/node_modules/polling-to-event/index.js:33:20)
    at /usr/lib/node_modules/homebridge-risco-alarm/app.js:74:17
    at /usr/lib/node_modules/homebridge-risco-alarm/app.js:281:17
    at <anonymous>

**Comment by szlaskidaniel** [comment]
Hi, you can try with new version, where Unhandled "error" event should be handled.

**Comment by platini76** [comment]
many and many log event.. only few pasted


_events:
   { end: [ [Function: responseOnEnd], [Function] ],
     close: [ [Function], [Function] ],
     data: [Function],
     error: [Function] },
  _eventsCount: 4,
  _maxListeners: undefined,
  socket:
   TLSSocket {
     _tlsOptions:
      { pipe: false,
        secureContext: [SecureContext],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: false,
        session:
         <Buffer 30 82 05 ca 02 01 01 02 02 03 03 04 02 c0 28 04 20 4c 01 00 00 8a da 04 dc 12 34 3e 6b ea 17 88 10 94 0e ef c4 09 55 42 e7 0f dc 1d 1b 3f 84 97 95 04 ... >,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     servername: 'www.riscocloud.com',
     alpnProtocol: false,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     _events:
      { close: [Array],
        end: [Function: onReadableStreamEnd],
        secure: [Function: onConnectSecure],
        free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener],
        finish: [Function] },
     _eventsCount: 8,
     connecting: false,
     _hadError: false,
     _handle:
      TLSWrap {
        _parent: [TCP],
        _parentWrap: undefined,
        _secureContext: [SecureContext],
        reading: true,
        onread: [Function: onStreamRead],
        onhandshakestart: [Function: noop],
        onhandshakedone: [Function: bound ],
        onocspresponse: [Function: onocspresponse],
        onerror: [Function: onerror],
        [Symbol(owner)]: [Circular] },
     _parent: null,
     _host: 'www.riscocloud.com',
     _readableState:
      ReadableState {
        objectMode: false,

**Comment by platini76** [comment]
you have reason! I had problem with number! now it is ok but riscoalarm don't respond to commands

[2018-10-13 16:07:00] [RiscoAlarm] New state detected: (3) -> DISARM. Notify!
/bin/sh: 1: npm: Permission denied


and when I try to arm:

[2018-10-13 16:10:26] [RiscoAlarm] Setting state to STAY_ARM
keep sid:u5g699bs
[2018-10-13 16:10:29] [RiscoAlarm] New Risco state set.
[2018-10-13 16:10:31] [RiscoAlarm] LoggedIn !
[2018-10-13 16:10:46] [RiscoAlarm] Setting state to AWAY_ARM
keep sid:u5g699bs

**Comment by szlaskidaniel** [comment]
/bin/sh: 1: npm: Permission denied looks like your environment issue. I run this code on RaspberryPi Homebridge docker version.
When set different status for Risco - only AWAY_ARM and OFF works.

**Comment by platini76** [comment]
how to resolve?

**Comment by platini76** [comment]
which dir? 
/usr/local/lib/node_modules/homebridge ?
this is my /usr/local/bin homebridge link

**Comment by szlaskidaniel** [comment]
run `npm update` inside main plugin folder (homebridge-risco-alarm) wherever it's installed

**Comment by platini76** [comment]
I dscover that in /var/homebridge/.node-gyp
there is 10.12 version..
how to cancel it and use 10.00?

**Comment by platini76** [comment]
at this point I doubt is permission on risco plugin:
ott 18 00:37:51 raspberry systemd[1]: Started Node.js HomeKit Server.
ott 18 00:38:05 raspberry homebridge[443]: /bin/sh: 1: npm: Permission denied
ott 17 22:38:07 raspberry homebridge[443]: [2018-10-18 00:38:07] Loaded config.json with 1 accessories and 5 platforms.
ott 17 22:38:07 raspberry homebridge[443]: [2018-10-17 22:38:07] ---
ott 17 22:38:13 raspberry homebridge[443]: [2018-10-17 22:38:13] Loaded plugin: homebridge-config-ui-x
ott 17 22:38:13 raspberry homebridge[443]: [2018-10-17 22:38:13] Registering platform 'homebridge-config-ui-x.config'
ott 17 22:38:13 raspberry homebridge[443]: [2018-10-17 22:38:13] ---
ott 17 22:38:13 raspberry homebridge[443]: [2018-10-17 22:38:13] Loaded plugin: homebridge-fritz-platform
ott 17 22:38:29 raspberry homebridge[443]: [2018-10-17 22:38:29] Registering platform 'homebridge-fritz-platform.FritzPlatform'
ott 17 22:38:29 raspberry homebridge[443]: [2018-10-17 22:38:29] ---
ott 17 22:38:34 raspberry homebridge[443]: [2018-10-17 22:38:34] Loaded plugin: homebridge-ifttt
ott 17 22:38:34 raspberry homebridge[443]: [2018-10-17 22:38:34] Registering platform 'homebridge-ifttt.IFTTT'
ott 17 22:38:34 raspberry homebridge[443]: [2018-10-17 22:38:34] ---
ott 17 22:38:39 raspberry homebridge[443]: [2018-10-17 22:38:39] Loaded plugin: homebridge-nest
ott 17 22:38:39 raspberry homebridge[443]: [2018-10-17 22:38:39] Registering platform 'homebridge-nest.Nest'
ott 17 22:38:39 raspberry homebridge[443]: [2018-10-17 22:38:39] ---
ott 17 22:38:41 raspberry homebridge[443]: [2018-10-17 22:38:41] Loaded plugin: homebridge-qnap-qvrpro
ott 17 22:38:41 raspberry homebridge[443]: [2018-10-17 22:38:41] Registering platform 'homebridge-QNAP-QVRPro.Camera-QNAP-QVRPro'
ott 17 22:38:41 raspberry homebridge[443]: [2018-10-17 22:38:41] ---
ott 17 22:38:46 raspberry homebridge[443]: [2018-10-17 22:38:46] Loaded plugin: homebridge-risco-alarm
ott 17 22:38:46 raspberry homebridge[443]: [2018-10-17 22:38:46] Registering accessory 'homebridge-risco-alarm.RiscoAlarm'
ott 17 22:38:46 raspberry homebridge[443]: [2018-10-17 22:38:46] ---

**Comment by szlaskidaniel** [comment]
it's a question to Risco dev guys ... 
generally inside package.json there is entry about required packages with their versions.

**Comment by szlaskidaniel** [comment]
close - as this is not related directly with the plugin
