### ISSUE TITLE
info on channel trigger

### ISSUE THREAD

**Issue by platini76** [szlaskidaniel/homebridge-risco-alarm#11]
Hello, it is possible to have separate channels and trig events?
example: I have 2 doors sensor... and I want to have them on my homekit...to trig light on and off... it is possible?

**Comment by andyblac** [comment]
@platini76 if you have those sensors on a separate partition, you could just add that single portion to HomeKit then do an automation based on if it is armed or not ?

![img_0189](https://user-images.githubusercontent.com/77936/52415630-71fd2580-2adf-11e9-8af3-37330c325187.jpg)
