### ISSUE TITLE
Clarity on Readme

### ISSUE THREAD

**Issue by ekkesa** [szlaskidaniel/homebridge-risco-alarm#12]
Hi,

Thank you for this! I was looking for something like this for quite a long time. I see you reference partitions at the bottom of the page, is it possible to provide some clarity on it.

"When set partitions for arm/disarm please use below schema: For all partitions actions use default "armed" and "disarmed" , for single partition use "1:armed" and "1:disarmed""

I have 4 partitions, which I use in different states.

E.g. Nobody home - All 4 partitions are armed (Presume **AWAY**)
Home at night (awake) - Outside Partitions armed (Presume **HOME**)
Home at night (sleeping) - 3/4 partitions armed (Presume **NIGHT**)
Home - All partitions disarmed (Presumed **OFF**)

Is this possible to set this using this plugin, if so how would the config.json look?

Thank you

**Comment by andyblac** [comment]
hi,

I have tweaked the authors code to allow this if you have multiple zones, if your interested in testing let me know.

it requires you to have your Risco setup as follows:

2 Partitions, 1 for house, 1 for outside. and the house 'Part-Set' needs to only set the sensors you require when in NIGHT mode.

my setup is as follows:

HOME = outside only
AWAY = all set
NIGHT = House in part set mode
OFF = all off.

**Comment by platini76** [comment]
> hi,
> 
> I have tweaked the authors code to allow this if you have multiple partitions, if you are interested in testing let me know.
> 
> it requires you to have your Risco setup as follows:
> 
> 2 Partitions, 1 for house, 1 for outside. and the house 'Part-Set' needs to only set the sensors you require when in NIGHT mode.
> 
> my setup is as follows:
> 
> HOME = outside only
> AWAY = all set
> NIGHT = House in part set mode
> OFF = all off.

I don't understand... if sensors are for your system "outside" are perimetral... and so... night must be set only "outside" sensors... and not "home"

**Comment by andyblac** [comment]
if you set, Home then Night, it will leave outside alone, thus have both alarmed. my garage is always alarmed unless I want to go in (thus OFF).

**Comment by andyblac** [comment]
```            "homeCommand": "1:armed",
            "armCommand": "0:armed",
            "partialCommand": "partially",
            "disarmCommand": "disarmed"
```

as you see I added 'homeCommand'

**Comment by andyblac** [comment]
it not perfect, but the best I can do with my little knowledge with Homebridge.

**Comment by ekkesa** [comment]
Unfortunately I have 4 partitions in my system and given the climate I cannot compromise the alarm system.

Would like to understand what you implemented to see if I can perhaps get it to work in my instance.
