### ISSUE TITLE
Multiple instances of plugin

### ISSUE THREAD

**Issue by andyblac** [szlaskidaniel/homebridge-risco-alarm#13]
I have setup multiple instances of plugin so I can show each partition in HomeKit. see snippet below. But if I set a partition it shows both as ARMED in HomeKit, is there anyway you can allow multiple instances of the plugin to be seen in HomeKit as separate Alarms.

``` 
       {
            "accessory": "RiscoAlarm",
            "name": "Home Alarm",
            "polling": true,
            "pollInterval": 15000,
            "riscoUsername": "*******",
            "riscoPassword": "*******",
            "riscoSiteId": *******,
            "riscoPIN": "*******",
            "armCommand": "0:armed",
            "disarmCommand": "0:disarmed"
        },
        {
            "accessory": "RiscoAlarm",
            "name": "Garage Alarm",
            "polling": true,
            "pollInterval": 15000,
            "riscoUsername": "*******",
            "riscoPassword": "*******",
            "riscoSiteId": *******,
            "riscoPIN": "*******",
            "armCommand": "1:armed",
            "disarmCommand": "1:disarmed"
        }
```

![img_0187](https://user-images.githubusercontent.com/77936/52415441-dc619600-2ade-11e9-8e43-9cd8325d5cf6.jpg)

**Comment by gawindx** [comment]
@andyblac, I think this release will provide a solution to state management.
I took as starting point your code (a few days ago) so your last changes will surely not all present.

For my part, the plugin seems to behave properly and I have tortured it in every way to try to flush out the errors.

If you can give me a return, I will correct any remaining errors and I will propose the code in pull request

[Multiple Instance version 'by Zone'](https://github.com/gawindx/homebridge-risco-alarm/tree/RiscoPanel-OO)

**Comment by andyblac** [comment]
yes, works sport on thanks.
