### ISSUE TITLE
can i use this as standalone?

### ISSUE THREAD

**Issue by pergolafabio** [szlaskidaniel/homebridge-risco-alarm#14]
i also have risco alarm system, but i dont use homebridge, but Home Asssistant instead
can i load this script/project as a standalone? maybe with a script or shell command or something? so i can retrieve the state and set the state?

thnx

**Comment by szlaskidaniel** [comment]
hi, yes it can be used as a module. You'll need to write your own nodejs service. expose a methods that you want to use like (arm / disarm) - and what's left is just call functions inside this solution.

**Comment by pergolafabio** [comment]
Well, I am not a developer ;( , but gonna learn it next year ;)... So that's a project for next year...


But anyway, I am already using/testing 2 other Risco projects I found on GitHub, they use indeed a nodejs service... But they both have the same issue... They do a polling, but the actual state of Risco is with a delay like 4-5 mins....

The problem is , when you arm/disarm, from a Risco hardware panel, you see on Riscocloud.com , in the overview page , the state changing in about 4-5 minutes,... 

When you change from the Risco app, then it's almost instant...
So do you get the state also from the overview page? Do you also have the same delay?

**Comment by szlaskidaniel** [comment]
I read status from:
`https://www.riscocloud.com/ELAS/WebUI/Overview/Get`
and
`https://www.riscocloud.com/ELAS/WebUI/Security/GetCPState`

I didn't notice delays tough.

**Comment by pergolafabio** [comment]
Well, that command does give you a delay... ;)

You can test it verry easy, just login in riscocloud.com , arm/disarm from a hardware panel... You see state changing in about 3-4 minutes...

Don't use the app while testing, that seems to push it instant
