### ISSUE TITLE
Public API verry soon available

### ISSUE THREAD

**Issue by pergolafabio** [szlaskidaniel/homebridge-risco-alarm#15]
good news guys, just got information that risco wil launch soon a public API for developers, they will inform me next week about ETA
seems they also finished integration with amazon alexa already, probably launching verry soon

**Comment by szlaskidaniel** [comment]
That’s a really good news ! Thank you for sharing

**Comment by pergolafabio** [comment]
will provide some more info when i have it, normally today or next week :)
indeed, good news, finally! :)

**Comment by pergolafabio** [comment]
found something already on their site now : 

https://www.riscogroup.com/products/solution/7815

Integrated Systems and Software Development Kit (SDK)
The SynopSYS Integrated Security & Building Management™ SDK enables driver development and third party integration.

The platform includes a comprehensive and flexible integrator toolbox for building professional synoptic maps and interactive buttons and allows full and immediate reaction to events. Device state logic and behavior (icon color, size, button appearance etc) can be easily customized. SynopSYS Integrated Security & Building Management™ allows full flexibility, tailoring a solution to requirements that may arise from specific project needs without the need to approach the vendor for special software development and adaptation. If needed, the System Integrator can even define onsite a unique behavior and scenario for specific devices according to Security Directors’ requests. This cost-effective solution shortens the implementation cycle of the project.

**Comment by szlaskidaniel** [comment]
I think this is quite old SDK :( , not really useful for us.
"SynopSYS Integrated Security & Building Management™ Driver SDK Programmer Guide" was released Installer Guides - Last Modified: 10/09/2018 - 16:45.

Unless you know something more about some kind of JSON based REST https API

**Comment by pergolafabio** [comment]
Yeah, I know, I was wrong about that sdk, that's why I removed the reply...
The cloud API that is going to be released, is indeed something new...

**Comment by szlaskidaniel** [comment]
ok. let's wait what they'll show. Thx for this tip.
