### ISSUE TITLE
Handle Zone

### ISSUE THREAD

**Issue by karan1686** [szlaskidaniel/homebridge-risco-alarm#16]
Is there any ways to handle zones? I got 1 partition with 4 zones (A,B,C,D) which arm different parts of the system

**Comment by andyblac** [comment]
the new merged code from @gawindx add this support, just add multiple configs for the required zones.

like my example:
```
        {
            "accessory": "RiscoAlarm",
            "name": "House Burglar Alarm",
            "polling": true,
            "pollInterval": 10000,
            "riscoUsername": "************",
            "riscoPassword": ".*******",
            "riscoSiteId": ******,
            "riscoPIN": "****",
            "armCommand": "armed",
            "homeCommand": "partially",
            "partialCommand": "partially",
            "disarmCommand": "disarmed",
            "riscoPartMode": true,
            "riscoPartId": 0
        },
        {
            "accessory": "RiscoAlarm",
            "name": "Garage Burglar Alarm",
            "polling": true,
            "pollInterval": 10000,
            "riscoUsername": "************",
            "riscoPassword": ".*******",
            "riscoSiteId": ******,
            "riscoPIN": "****",
            "armCommand": "armed",
            "homeCommand": "partially",
            "partialCommand": "partially",
            "disarmCommand": "disarmed",
            "riscoPartMode": true,
            "riscoPartId": 1
        }
```

**Comment by karan1686** [comment]
Thanks for the information.  I have updated the plugin now. 

I have got it to arm all partitions now. But when I try to create a second config for Zone C for example. I used Partid:3 l, but doesn’t arm just C with this config. 

Have I got that partid part correct?

Thanks again

**Comment by andyblac** [comment]
> Thanks for the information. I have updated the plugin now.
> 
> I have got it to arm all partitions now. But when I try to create a second config for Zone C for example. I used Partid:3 l, but doesn’t arm just C with this config.
> 
> Have I got that partid part correct?
> 
> Thanks again

post your config I'll have a look, (remove username, pass, pin etc)

**Comment by karan1686** [comment]
Please see below


        {
            "accessory": "RiscoAlarm",
            "name": "Whole House Burglar Alarm",
            "polling": true,
            "pollInterval": 10000,
            "riscoUsername": "",
            "riscoPassword": "",
            "riscoSiteId": ,
            "riscoPIN": "",
            "armCommand": "armed",
            "homeCommand": "partially",
            "partialCommand": "partially",
            "disarmCommand": "disarmed",
            "riscoPartMode": true,
            "riscoPartId": 0
        },
       {
            "accessory": "RiscoAlarm",
            "name": "Downstairs Burglar Alarm",
            "polling": true,
            "pollInterval": 10000,
            "riscoUsername": "",
            "riscoPassword": "",
            "riscoSiteId": ,
            "riscoPIN": "",
            "armCommand": "armed",
            "homeCommand": "partially",
            "partialCommand": "partially",
            "disarmCommand": "disarmed",
            "riscoPartMode": true,
            "riscoPartId": 3
        }


           
![74A285F0-F795-4B9D-AA56-4D918FECCF0C](https://user-images.githubusercontent.com/4659203/65834526-c013a300-e2d3-11e9-8e19-daa6ac755a47.jpeg)
### ![A59FA192-2F83-4102-A389-C4D874421CA1](https://user-images.githubusercontent.com/4659203/65834527-c013a300-e2d3-11e9-9547-78f0a5bcb92f.jpeg)

**Comment by andyblac** [comment]
ok, this update only sets `partitions` not `groups`, as you only have 1 partition it will not allow you to control your groups, tbh I don't even know what those are or how they are used in the Risco app.

**Comment by karan1686** [comment]
Okay fair enough that make sense now. 

This is how it was configured by the installer, so not sure how to change it now

**Comment by andyblac** [comment]
Give him a call, he should be able to change it remotely for you.

**Comment by karan1686** [comment]
Yeah I will try that. Thanks for your help so far.

**Comment by szlaskidaniel** [comment]
Close Issue as the discussion stopped.
