### ISSUE TITLE
login [step1] > error: Username/Password mismatch

### ISSUE THREAD

**Issue by tomdoherty** [szlaskidaniel/homebridge-risco-alarm#17]
Hi
As of today, with no changes to my configs, I see the above.

I can login to risco cloud as normal using the same username/password/pin

Am I the only one?

Thanks

**Comment by andyblac** [comment]
no, I'm  getting the same

```[9/19/2019, 1:38:34 AM] [House Burglar Alarm] Login failed
[9/19/2019, 1:38:49 AM] [House Burglar Alarm] Status Code:  200
[9/19/2019, 1:38:49 AM] [House Burglar Alarm] login [step1] > error:
                                    Username/Password mismatch
                                        <br />Try again
```

**Comment by megajeff75** [comment]
Risco sent out an email to everyone saying they were updating their website and app. The app now does FaceID etc. The website has been updated so the plug in will need to be updated to work with the new web pages.

**Comment by tomdoherty** [comment]
Hi

I intercepted the POST request for the login and it looks the same. Hoping they haven’t introduced js or something to thwart us

**Comment by szlaskidaniel** [comment]
That’s bad news, I ve got the same, happen during leaving for vacations:( 
I will check it but in the end of the month when I back home.

**Comment by tomdoherty** [comment]
Thanks Daniel. I’ll have a try but I’m getting married in a couple of days and then honeymoon 


Thanks for your work on this - it’s been so useful we’ve come to rely on it

**Comment by megajeff75** [comment]
I can't code to save my life but what the hell. In the meantime time permitting I'll take a gander into it.

**Comment by pergolafabio** [comment]
yeah, something changed in 5.2 cloud
lucas version is also impacted https://github.com/lucacalcaterra/risco-mqtt-bridge
this bridge (home assistant addon) is still working : https://github.com/martingrayson/risco-hass-bridge

**Comment by andyblac** [comment]
wish I knew how to code js, I know python but not js. :(

**Comment by gawindx** [comment]
Hello

I also encounter the same problem but by doing some research and adaptations I managed to pass the problem with the following code (login function in file risco.js) :

function login() {
    return new Promise(function (resolve, reject) {
        //self.log('login [step1] to RiscoCloud first stage...');
        var post_data = 'username=' + risco_username + '&password=' + risco_password; 
        var options = {
            url: 'https://www.riscocloud.com/ELAS/WebUI/',
            method: 'POST',
            headers: {
                'Content-Length': post_data.length,
                'Content-type': 'application/x-www-form-urlencoded'
                },
            body: post_data
        };

        request(options, function (err, res, body) {
            try {
                if (!err && res.statusCode == 302) {
                    //self.log('Got Cookie, save it');
                    riscoCookies = res.headers['set-cookie'];

									 
                    var post_data = 'SelectedSiteId=' + risco_siteId + '&Pin='+ risco_pincode;

                    var options = {
                        url: 'https://www.riscocloud.com/ELAS/WebUI/SiteLogin',
                        method: 'POST',
                        headers: {
                            'Cookie': riscoCookies,
                            'Host': 'www.riscocloud.com',
                            'Origin': 'https://www.riscocloud.com',
                            'Referer': 'https://www.riscocloud.com/ELAS/WebUI/SiteLogin/Index',
                            'Content-Length': post_data.length,
                            'Content-type': 'application/x-www-form-urlencoded'
                        },
                        body: post_data
                    };
                    request(options, function (err, res, body) {
                        try {
                            if (!err && res.statusCode == 302) {
                                self.log('LoggedIn !');
                                self.log('Location :' +res.headers['Location'])
                                resolve();
                                return
                            } else {
                                self.log('Status Code: ', res.statusCode);
                                self.log('login [step2] > error:', extractError(body));
                                reject('');
                                return
                            }

                        } catch (error) {
                            self.log(error);
                            reject('');
                            return
                        }
                    })

                } else {
                    self.log('Status Code: ', res.statusCode);
                    self.log('login [step1] > error:', extractError(body));
                    reject('');
                    return
                }
            } catch (error) {
                self.log(error);
                reject('');
                return
            }
        })
    });
}

**Comment by andyblac** [comment]
@gawindx nice one seems work here also, but `OngoingAlarm` is still not functioning, can you confirm ?

```[9/20/2019, 1:29:35 AM] [House Burglar Alarm] RiscoCloud ArmedState:1 Partition / RiscoCloud OngoingAlarm: undefined
[9/20/2019, 1:29:35 AM] [House Burglar Alarm] Actual state is: (3) ->  DISARM
```

**Comment by andyblac** [comment]
ok fixed TRIGGERED. and applied @gawindx patch here is my files, I have also tweaked code to support 'HOME' in config `"homeCommand": "1:armed",` allowed you to set a separate zone for HOME in HomeKit.

the only downside to `HOME` is HomeKit can not see zones, so I have assumed you have multiple Zones, it is coded that if 1 zone, is armed it assumes HOME is armed, and if you have more than 1 Zone armed it assumed AWAY is set.

hope it help some people.

2 zip file one with `home` support, and one with out.

[home-support.zip](https://github.com/szlaskidaniel/homebridge-risco-alarm/files/3633641/home-support.zip)
[risco.zip](https://github.com/szlaskidaniel/homebridge-risco-alarm/files/3633642/risco.zip)

**Comment by gawindx** [comment]
unfortunately, I can not confirm for the moment any problem with state "ongoingalarm"
on the other hand, I could run a few tests this weekend and see what that gives. if there is indeed a problem and I can solve it, I will share the correction.

**Comment by tomdoherty** [comment]
@andyblac hi Andy, I tried the risco.zip but it fails to modify the actual state of my alarm. Does it work for you?

**Comment by andyblac** [comment]
@tomdoherty did set on panel ? just not display in homekit ?

**Comment by andyblac** [comment]
@tomdoherty hmm your right, did not check I was focused on HomeKit last night lol.

**Comment by tomdoherty** [comment]
Hey @andyblac I tried arming the alarm using HomeKit. It fails to arm. When I arm it manually it picks up the new state so you’ve fixed the original issue but this is a new one 😊

**Comment by andyblac** [comment]
@tomdoherty got it working, just cleaning up debug logs, I'll post soon

**Comment by andyblac** [comment]
@tomdoherty try this one, I had to use @gawindx tweak to fix arm/disarm too.

[risco.zip](https://github.com/szlaskidaniel/homebridge-risco-alarm/files/3634818/risco.zip)

**Comment by pergolafabio** [comment]
if its helpfull, i am using this bridge
that one is still working, there was even no code change needed, i am using it with cloud 5.2 , getting status is still working, as well the commands to arm/disarm

https://github.com/martingrayson/risco-hass-bridge

**Comment by gawindx** [comment]
tests that I realized to solve the problem, the header "content-length" seems very important, as well as the fact of not sending data json for the login

**Comment by lucacalcaterra** [comment]
> tests that I realized to solve the problem, the header "content-length" seems very important, as well as the fact of not sending data json for the login

content-lenght is not sets on my app and it works. Instead i'm find that the solution is the second you wrote (not sending json !!!!)

**Comment by lucacalcaterra** [comment]
Eureka ! Works! thanks to @gawindx for the solution. the body of request !!!

**Comment by andyblac** [comment]
@gawindx do you think it would be possible to get Armed status from `SECURITY` page instead of `Overview` System Status partitions armed ?

![Screenshot 2019-09-20 at 12 24 00](https://user-images.githubusercontent.com/77936/65323562-9656cf80-dba1-11e9-8c31-4fe7bd71a95c.jpg)
![Screenshot 2019-09-20 at 12 23 51](https://user-images.githubusercontent.com/77936/65323563-9656cf80-dba1-11e9-8c85-ad2d53b1e5bb.jpg)

**Comment by pergolafabio** [comment]
Yes, if arming from a Risco panel, then the state is indeed delayed for like 4-5 min... Although, the event is coming in directly

**Comment by gawindx** [comment]
I do not just think so, I'm sure. I was working on this possibility when Risco updated their cloud. To be more precise, I'm working on having a mode 'by zone'

**Comment by andyblac** [comment]
> Yes, if arming from a Risco panel, then the state is indeed delayed for like 4-5 min... Although, the event is coming in directly

in this plugin ??, mine takes seconds, do you have polling enabled ?

```            "polling": true,
            "pollInterval": 10000,
```

**Comment by andyblac** [comment]
> I do not just think so, I'm sure. I was working on this possibility when Risco updated their cloud. To be more precise, I'm working on having a mode 'by zone'

that would be good, as a work around I have duplicated the plugin so I have Alarms `House & Garage', but the down side it that I have to use if partitions > 0 or > 1 for each, that means garage works ok, but for house I have to have arm both so HomeKit see's when it armed.

**Comment by pergolafabio** [comment]
> > Yes, if arming from a Risco panel, then the state is indeed delayed for like 4-5 min... Although, the event is coming in directly
> 
> in this plugin ??, mine takes seconds, do you have polling enabled ?
> 
> ```
>             "polling": true,
>             "pollInterval": 10000,
> ```

no, i dont use homekit, i use home assistant :)
but the behaviour is the same, you can easely check
so arm/disarm from a risco hardware panel, login to riscocloud.clom, arm with the panel...
see the slider in the overview only changing after about 4-5 min....
if you arm/disarm from the risco app on adroid , the slider on the overview page will change instantly ...

**Comment by andyblac** [comment]
> > > Yes, if arming from a Risco panel, then the state is indeed delayed for like 4-5 min... Although, the event is coming in directly
> > 
> > 
> > in this plugin ??, mine takes seconds, do you have polling enabled ?
> > ```
> >             "polling": true,
> >             "pollInterval": 10000,
> > ```
> 
> no, i dont use homekit, i use home assistant :)
> but the behaviour is the same, you can easely check
> so arm/disarm from a risco hardware panel, login to riscocloud.clom, arm with the panel...
> see the slider in the overview only changing after about 4-5 min....
> if you arm/disarm from the risco app on adroid , the slider on the overview page will change instantly ...

ye works instantly here.

**Comment by pergolafabio** [comment]
yeah, i mean that buttons, it isnt a slider indeed
but maybe the behaviour changed in 5.2 ...
before, if i arm from my panel, you see that buttin from green to red, changing after 4-5 min
if you open the app, then its instant

**Comment by andyblac** [comment]
@pergolafabio just a few tests, and as soon as I arm/disarm on my Risco panel, my web page update after a refresh, iPhone app update., HomeKit and emails come through.

this has always been the case here.

**Comment by pergolafabio** [comment]
yeah, but while testing, close your app on android/iphone, otherwise the change is indeed instant... app should be closed
but again, maybe the behaviour changed in 5.2 cloud update

**Comment by andyblac** [comment]
> yeah, but while testing, close your app on android/iphone, otherwise the change is indeed instant... app should be closed
> but again, maybe the behaviour changed in 5.2 cloud update

app was forced quit, when testing.

**Comment by andyblac** [comment]
just tested again, page updates instantly here not matter what you do.

**Comment by pergolafabio** [comment]
strange, ill test again when i am home :)
but anyway, there will be a public API available soon, then code needs to be changed again, and integration will be easier :)

**Comment by andyblac** [comment]
> strange, ill test again when i am home :)
> but anyway, there will be a public API available soon, then code needs to be changed again, and integration will be easier :)

oh cool where you get that info from ?

**Comment by pergolafabio** [comment]
risco itself, i quote the last mail : 

```
Sorry for the late reply. I was asking a bit around and I would like to explain the reason and give you some information about the plan.
Currently, we don’t have a method to monitor the API clients. This means that if we make the API public, people will be able to make as much use of it as they want without any limitations, and we will not be able to monitor it. The resulted loads might make us add more servers and increase the cloud costs - a service that is currently provided for free to all of our customers.
In the near roadmap we are going to add a client key to the API which will allow us to monitor from which client the requests are coming and decide whether scaling or limiting is required. This feature will allow us to open the API to the public.
I’ll update you as soon as this feature is available. If there is a specific need for the API now, let me know what it is and maybe we could help.
```

**Comment by andyblac** [comment]
> risco itself, i quote the last mail :
> 
> ```
> Sorry for the late reply. I was asking a bit around and I would like to explain the reason and give you some information about the plan.
> Currently, we don’t have a method to monitor the API clients. This means that if we make the API public, people will be able to make as much use of it as they want without any limitations, and we will not be able to monitor it. The resulted loads might make us add more servers and increase the cloud costs - a service that is currently provided for free to all of our customers.
> In the near roadmap we are going to add a client key to the API which will allow us to monitor from which client the requests are coming and decide whether scaling or limiting is required. This feature will allow us to open the API to the public.
> I’ll update you as soon as this feature is available. If there is a specific need for the API now, let me know what it is and maybe we could help.
> ```

thanks.

**Comment by lucacalcaterra** [comment]
> risco itself, i quote the last mail :
> 
> ```
> Sorry for the late reply. I was asking a bit around and I would like to explain the reason and give you some information about the plan.
> Currently, we don’t have a method to monitor the API clients. This means that if we make the API public, people will be able to make as much use of it as they want without any limitations, and we will not be able to monitor it. The resulted loads might make us add more servers and increase the cloud costs - a service that is currently provided for free to all of our customers.
> In the near roadmap we are going to add a client key to the API which will allow us to monitor from which client the requests are coming and decide whether scaling or limiting is required. This feature will allow us to open the API to the public.
> I’ll update you as soon as this feature is available. If there is a specific need for the API now, let me know what it is and maybe we could help.
> ```

Reading it... my opinion is that is not a near future thing ...  but it's only my personal advice

**Comment by pergolafabio** [comment]
Will see ;) I asked again for eta, and also private API again

**Comment by megajeff75** [comment]
Hey Andy,
Thanks mate. I've tried your files however it doesn't work for me? I still
seem to be getting username/password mismatch three times then lockout.

I've replaced the two .js files in the
/homebridge/node_modules/homebridge-risco-alarm/

not sure what I might have done wrong. Restarted, checked my config in
homebridge was as before.

**Comment by gawindx** [comment]
@lucacalcaterra  and @pergolafabio 
I do not think it will be tomorrow either.
In France (and certainly not only in France), Risco has a program to reward big installers / customers (in terms of turnover)
One of their advantages is the possibility of deploying a personalized smartphone application (logo, color, etc ...).

If they open their APIs, anyone can use it and create their own application. This could impact some of their economic model.

But for me too, it's only my personal opinion and I think we're moving away from the basic topic.

**Comment by andyblac** [comment]
> Hey Andy, Thanks mate. I've tried your files however it doesn't work for me? I still seem to be getting username/password mismatch three times then lockout. I've replaced the two .js files in the /homebridge/node_modules/homebridge-risco-alarm/ not sure what I might have done wrong. Restarted, checked my config in homebridge was as before.
> […](#)

if your getting locked out then it is sending username / password to risco, check your config make sure there correct.

just to be sure this is last file linked above https://github.com/szlaskidaniel/homebridge-risco-alarm/files/3634818/risco.zip

**Comment by megajeff75** [comment]
Thanks Andy. I can't make the changes work. I did a file compare between
the files and I'm definitely using your new version. I've copied and pasted
the username, password, pin from config file (the same configuration that
was working and is unchanged). No worries, I'll wait for the official fix
release in good time.

**Comment by andyblac** [comment]
@megajeff75 send me your file, I'll just add the user / pass change for you.

**Comment by andyblac** [comment]
@pergolafabio I have been doing loads of tests, it seems your where right, but even worse the app is the same, for I did the following, force close app, BUT WAIT AT LEAST 5 MINS, so the authentication has timed out, then arm the alarm via the panel, once it is set open the Risco App, the app will NOT show the real current status, It shows as disarmed, once you change the Armed status on the phone as you have to authenticate (for me via faceid), everything works from the panel to the phone / web, until the authentication timeout again. So to me it seems Risco has a bug in their new App / Web 5.2.

**Comment by andyblac** [comment]
just emailed Risco with below.

```
Hi, 

I have a problem with your new iPhone app and update RiscoCloud.com, if the new app has not been launched on the iPhone (closed not just hidden) for some time (at least 10 mins), when you launch the the app it does NOT show the real current status of the panel.

1: make sure the app on the iPhone has been installed and setup to use FaceID.
2: close the app (not just hidden).
3: wait 10mins
4: goto you Risco panel and arm the alarm, wait for the 30sec count down so the alarm is actually armed.
5: open the Risco app on the iPhone, as the app was previously logged in and setup for FaceID, the app should just open to the Security page to display the panel status. notice that the status will be GREEN (disarmed) it does not update.

this must be a bug!!!. now continue on

6: set the Alarm to ARMED in the app by swiping the slider right to RED.
7: the app asks for you to confirm your identity by using FaceID.
8: the armed status updates, to what is real.
9: now disarm the alarm via the Risco panel.
10: the app now responds correctly, to anything the Risco panel does.

you can also try the above, but start with app open on before setting Alarm on panel,

1: make sure the app on the iPhone has been installed and setup to use FaceID.
2: close the app (not just hidden).
3: wait 10mins
4: open the Risco app on the iPhone, as the app was previously logged in and setup for FaceID, the app should just open to the Security page to display the panel status. notice that the status will be GREEN (disarmed).
5: goto you Risco panel and arm the alarm, wait for the 30sec count down so the alarm is actually armed.
6: check the iPhone app, notice that it does not update.

this must be a bug!!!. now continue on

7: set the Alarm to ARMED in the app by swiping the slider right to RED.
8: the app asks for you to confirm your identity by using FaceID.
9: the armed status updates, to what is real.
10: now disarm the alarm via the Risco panel.
11: the app now responds correctly, to anything the Risco panel does.



This bug means you do not get any app notifications unless the app has been authenticated, but as soon as it times out, the everything stops working.

This above is also the same when using the RiscoCloud.com, everything used to work fine unless recently.


I would appreciate it if can can acknowledge this email and let me know any progress you make, If I can be of any help to you in Testing / Debugging please feel free to contact me via email or phone.

Regards
```

**Comment by pergolafabio** [comment]
Yeah, I know, but now it seems even worse then? Before , if I open app, i saw the real status...

**Comment by pergolafabio** [comment]
Before 5.2, when I armed from a panel, if I opened the app after the walk out timer was complete, the app showed the real status, do that's not true anymore now?

**Comment by andyblac** [comment]
correct, app does not show the count down then slide over to armed, unless you 1st give it your FaceID by manually setting from the app.

Then it will work until the authentication times out.

this also means you get No Alarm notifications when app is closed in back ground.

**Comment by andyblac** [comment]
just got off phone with my alarm installer, he has asked me to ask someone with Android Phones to see if it happens on that too, or is it just an iPhone issues,

Can anyone here with an Android Phone check my above procedure and report back.

**Comment by pergolafabio** [comment]
Android doesn't have faceid.. ;)

**Comment by andyblac** [comment]
@pergolafabio ye I know but just the app work without need to enter the PIN ??

**Comment by pergolafabio** [comment]
Yeah, to arm/disarm I need to enter pin... But can't test this weekend, maybe someone else

**Comment by pergolafabio** [comment]
But I can open the app without need to enter pin, maybe that's different then on iPhone?

**Comment by andyblac** [comment]
I mean on my iPad min 2 (no FaceID) if I just open the app, and try to set alarm via panel, the app does NOT show new status, until I first manually set the alarm 1st, then because I have entered my PIN, if I try to reset the Alarm on the panel, the app works fine.

**Comment by andyblac** [comment]
> But I can open the app without need to enter pin, maybe that's different then on iPhone?

yes, on iPad / iPhone you can open the app, without entering anything, it only asks for a PIN on arming / disarming.

**Comment by pergolafabio** [comment]
Btw, public API will be released probably this year, just got new Intel ...

**Comment by andyblac** [comment]
@tomdoherty try files from here, these are the original file, just with login update https://github.com/andyblac/homebridge-risco-alarm/tree/master-login-fixed

**Comment by andyblac** [comment]
@szlaskidaniel you can try my new refactored version, that gets correct Control Panel state and Alarm state, i have optimised code quite a bit.  
https://github.com/andyblac/homebridge-risco-alarm/tree/master-cleanup

If you want a Pull Request just ask.

**Comment by megajeff75** [comment]
So my issue would seem to be related to password characters that cannot be
sent programmatically via many of the risco addons including this one and
risco-mqtt-bridge. I determined that having a "&" within the password
breaks the transmission of the password. When I edited the password to take
out that character the risco-mqtt-bridge then worked. Presume this one
would too now. This character is accepted in the browser by Risco so I
presume the processing of that character in .js is a problem? I could
google it but hey :)

Cheers
Jeff

**Comment by andyblac** [comment]
> So my issue would seem to be related to password characters that cannot be sent programmatically via many of the risco addons including this one and risco-mqtt-bridge. I determined that having a "&" within the password breaks the transmission of the password. When I edited the password to take out that character the risco-mqtt-bridge then worked. Presume this one would too now. This character is accepted in the browser by Risco so I presume the processing of that character in .js is a problem? I could google it but hey :) Cheers Jeff
> […](#)

glad you got it working, have you tried my optimised version ?, seems too be running very well here, and I now get alerts if alarm goes off, something that seems to be broken in the original version.

**Comment by rp1989** [comment]
Hi @andyblac, i just installed the master-cleanup but i am still getting the Username/password mismatch error when starting homebridge. Any ideas please?

**Comment by megajeff75** [comment]
Try using a simple password  for testing (smaller, less fancy characters).
I removed the ampersand from my password and it worked. Didn’t check if
that was due to the length reducing by one character or the character
itself. I got it to work after having similar issues.

**Comment by rp1989** [comment]
Hi @megajeff75, i tried changing this but the requirement for the password is to have a uppercase letter, a number and a special character when changing the password. I have set this to ‘Testing01-‘ but still getting the login failed error.

**Comment by andyblac** [comment]
> Hi @megajeff75, i tried changing this but the requirement for the password is to have a uppercase letter, a number and a special character when changing the password. I have set this to ‘Testing01-‘ but still getting the login failed error.

try using html escape code likes `&amp;` for `&` in the config.

**Comment by andyblac** [comment]
@rp1989 @megajeff75 can you both try https://github.com/andyblac/homebridge-risco-alarm/tree/master-login-pass-encode-test this branch to see if it fixes the special chars in passwords failing, 

Thanks.

**Comment by andyblac** [comment]
just had word back RISCO, they have fixed the issue I emailed them about, so now panel to app now works again, and thus panel to this plugin is also fixed.

```
[9/25/2019, 4:22:26 PM] [Garage Burglar Alarm] New state detected: (3) -> DISARM. Notify!
[9/25/2019, 4:22:27 PM] [Garage Burglar Alarm] Setting state to DISARM
[9/25/2019, 4:22:29 PM] [Garage Burglar Alarm] Risco state updated
[9/25/2019, 4:22:56 PM] [Garage Burglar Alarm] New state detected: (1) -> AWAY_ARM. Notify!
[9/25/2019, 4:22:57 PM] [Garage Burglar Alarm] Setting state to AWAY_ARM
[9/25/2019, 4:22:59 PM] [Garage Burglar Alarm] Risco state updated
```

**Comment by rp1989** [comment]
Seems to be all working now thank you! Will need to test the states properly tomorrow. Will report back once i have had a chance to test.

**Comment by andyblac** [comment]
> Seems to be all working now thank you! Will need to test the states properly tomorrow. Will report back once i have had a chance to test.

Thanks, if all working, I'll create a Pull Request for @szlaskidaniel from my cleanup branch (as I have merged the login fix into that).

Just let me know how you get on in your tests.

again thanks.
Andy.

**Comment by rp1989** [comment]
Hi @andyblac i have tested everything today and can confirm everything seems to be working as expected. The states all work on homekit and password can have & or any other characters without any issues. Thanks you for all your help with this!

**Comment by andyblac** [comment]
> Hi @andyblac i have tested everything today and can confirm everything seems to be working as expected. The states all work on homekit and password can have & or any other characters without any issues. Thanks you for all your help with this!

no problem, glad I could help, I'll create a pull request for @szlaskidaniel incase he just wants to pull my changes.

**Comment by aecom** [comment]
Hi
How do I install this

Thanks

Eliran Moshe®
Sent from my iPhone  PR⭕️  ma❌

**Comment by andyblac** [comment]
@aecom my updates ? here unzip this file and FTP the 2 js files into the plugin folder on your homebridge install folder.

[updates.zip](https://github.com/szlaskidaniel/homebridge-risco-alarm/files/3661896/updates.zip)

**Comment by aecom** [comment]
Don’t I have to change config ??
To add new alarm partitions??
Thanks

Eliran Moshe®
Sent from my iPhone  PR⭕️  ma❌

**Comment by andyblac** [comment]
> Don’t I have to change config ?? To add new alarm partitions?? Thanks Eliran Moshe® Sent from my iPhone PR⭕️ ma❌
> […](#)

no, original config will work fine.

**Comment by steenbar81** [comment]
Hi. I am pretty new to this, I haven't been able to get my homebridge to log in since this reported change. When I found this thread I thought I would be able to fix it but I am still getting the same warning. I have tried using these files you suggest Andy, but I am not too sure what I am doing with them. Can anyone help me?

thanks... Stevie

[9/29/2019, 6:30:05 PM] [RiscoAlarm] Status Code:  200
[9/29/2019, 6:30:05 PM] [RiscoAlarm] login [step1] > error: 
                                    Username/Password mismatch
                                        <br />Try again                         
[9/29/2019, 6:30:05 PM] [RiscoAlarm] Login failed

**Comment by andyblac** [comment]
download to new files from git, try those.

**Comment by steenbar81** [comment]
I think it might be the last bit where I am failing. I downloaded the 2 files, the Mac unzipped them and I dragged them into the .homebridge folder (where the config is?) but no change. Same error.

**Comment by andyblac** [comment]
they need to go in the plugin folder inside `node_modules` check these 2 locations

`/usr/lib/node_modules/homebridge-risco-alarm` or `/home/pi/node_modules/homebridge-risco-alarm`

**Comment by steenbar81** [comment]
Sorry Andy, might be beyond me this. I input that and for each location it says "no such file or directory"

**Comment by steenbar81** [comment]
I think I have it, thanks for your help Andy. Much appreciated.

**Comment by steenbar81** [comment]
and now I'm getting a CAD-8 error message, doh!!

**Comment by szlaskidaniel** [comment]
closing this thread as original issue was solved. 
Thanks all to that participated and helped here.
