### ISSUE TITLE
Issue when alarm is Trigged

### ISSUE THREAD

**Issue by andyblac** [szlaskidaniel/homebridge-risco-alarm#21]
when the alarm is going off aka triggered, HomeKit's tile does say triggered, BUT, a long pressing on the title brings up the dialog that shows OFF highlighted, so in order to cancel the alarm one has to 1st set and then unset the alarm by choosing AWAY, then OFF.

Is this a HomeKt issue or an issue the with the plugin ?

**Comment by szlaskidaniel** [comment]
Hi, I believe it's HomeKit stuff. 
Plugin is able to only change states (Home / Away / etc) , once new state is received, it execute command on Risco page. There is no implemented "Turn Off Alarm" HTTPS request from Plugin to Risco as there is no available Button on HomeKit to allow me to do that.

**Comment by andyblac** [comment]
but why does the the alarm in HomeKit switch to OFF and not stay on AWAY in HomeKit?

**Comment by szlaskidaniel** [comment]
I didn't tested that approach long time ago, not sure how to "Turn it off from HomeKit".

In theory code is ready for that:
`var riscoState;
                // 0 -  Characteristic.SecuritySystemTargetState.STAY_ARM:
                // 1 -  Characteristic.SecuritySystemTargetState.AWAY_ARM:
                // 2-   Characteristic.SecuritySystemTargetState.NIGHT_ARM:
                // 3 -  Characteristic.SecuritySystemTargetState.DISARM:
                //logger.debug(body);

                if (body.OngoingAlarm == true) {
                    riscoState = 4;`

**Comment by andyblac** [comment]
yes. we are setting 4, that is TRIGGER in HomeKit, so it looks like 4 in the action screen (HOME, NIGHT, AWAY, OFF) default to OFF and not keeping the original state. I guess there is nothing we can do.

**Comment by andyblac** [comment]
looking to https://github.com/KhaosT/HAP-NodeJS/blob/bb0c5b9af02e40b3ee7fc2352eb5ada20b369c68/src/lib/gen/HomeKit.ts#L2045

```inherits(Characteristic.SecuritySystemTargetState, Characteristic);

Characteristic.SecuritySystemTargetState.UUID = '00000067-0000-1000-8000-0026BB765291';

// The value property of SecuritySystemTargetState must be one of the following:
Characteristic.SecuritySystemTargetState.STAY_ARM = 0;
Characteristic.SecuritySystemTargetState.AWAY_ARM = 1;
Characteristic.SecuritySystemTargetState.NIGHT_ARM = 2;
Characteristic.SecuritySystemTargetState.DISARM = 3;
```


it does not support 4 so where is TRIGGER set ?

**Comment by andyblac** [comment]
oh found it here https://github.com/KhaosT/HAP-NodeJS/blob/HEAD/src/lib/gen/HomeKit.ts#L2015

**Comment by andyblac** [comment]
so it does look like a HomeKit issue not Homebridge or this plugin.

**Comment by szlaskidaniel** [comment]
yep, correct. I don't think we could do anything with this

**Comment by jacquese97** [comment]
> but why does the the alarm in HomeKit switch to OFF and not stay on AWAY in HomeKit?
> 
> at least then we could simply press OFF to turn off alarm
