### ISSUE TITLE
Not responding since ios13

### ISSUE THREAD

**Issue by dbiphoner** [szlaskidaniel/homebridge-risco-alarm#22]
Hello,

Since i am on ios13 the riscoalarm accesory is not responding anymore.

**Comment by andyblac** [comment]
more info?, you mean Homekit is only saying "Not Responding" ??

it seems ok for me.

**Comment by dbiphoner** [comment]
I am using version 1.2.5

this is config

        {
            "accessory": "RiscoAlarm",
            "name": "RiscoAlarm",
            "polling": true,
            "pollInterval": 15000,
            "riscoUsername": "xxx",
            "riscoPassword": "xxx",
            "riscoSiteId": xxxxxx,
            "riscoPIN": "xxxx",
            "armCommand": "armed",
            "partialCommand": "partially",
            "homeCommand": "partially",
            "disarmCommand": "disarmed",
            "riscoPartMode": false,
            "riscoPartId": 0
        },

I have never changed anything else then the update of the plugin

I could be that's its since the cloud update. I didn't use the plugin for some time

grtz

**Comment by andyblac** [comment]
then you need to update the plugin with the version in git, not via npm.

**Comment by dbiphoner** [comment]
I tried to change the passwordt to... no luck

**Comment by andyblac** [comment]
> I tried to change the passwordt to... no luck

password is not the issue, you need to use git version.

**Comment by gawindx** [comment]
This is exactly like the problem that occurred when Risco updated the Cloud.

You should check that the contents of the risco.js and app.js files correspond to the current file on this github (last version).

If they are not the same then your problem would be identified.

On the other hand if the files are very identical, one will be able to conclude that you face a new problem still unidentified.

Subsidiary question, no special characters in your password (or login)?

@andyblac beat me but I post it even

**Comment by dbiphoner** [comment]
yes there @ in the pasword, but that always has been.

How do i perform update with git?

grtz

**Comment by andyblac** [comment]
download the zip, https://github.com/szlaskidaniel/homebridge-risco-alarm/archive/master.zip unzip and FTP to your plugin folder on your homebridge setup.

**Comment by dbiphoner** [comment]
i am using docker container on synlogy NAS, i have to look into that

**Comment by dbiphoner** [comment]
ok problem fixed thanks!!

**Comment by andyblac** [comment]
good to here, can you close ticket :)

**Comment by dbiphoner** [comment]
Thanx
