### ISSUE TITLE
Username/password mismatch

### ISSUE THREAD

**Issue by reinierkops** [szlaskidaniel/homebridge-risco-alarm#23]
When i see the logging, i get this error:
 login [step1] > error:
                                    Username/Password mismatch
<br />Try again | stdout
-- | --

While i'm sure the username/password is correct

**Comment by andyblac** [comment]
update plugin, use the version in GitHub, the version in NPM is not the latest, use the link below to download from github and install manually.

https://github.com/szlaskidaniel/homebridge-risco-alarm/archive/master.zip

**Comment by reinierkops** [comment]
Thanks, that the solution!
