### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by soulcook** [szlaskidaniel/homebridge-risco-alarm#24]
Hi

Great to have this plugin available, but unfortunately it doesn't seem to be working. I am 100% certain that I have entered my username and password correctly in the config, and these work fine when I login via the RISCO web interface, but on startup and every time the plugin tries to poll I get the following log message:

> [3/10/2020, 1:18:28 PM] [RiscoAlarm] login [step1] > error: 
>                                     Username/Password mismatch
>                                         <br />Try again                         
> [3/10/2020, 1:18:28 PM] [RiscoAlarm] Login failed 

I've checked the config block several times and I'm pretty sure everything is correct. Any idea what's going on?

Thanks!

**Comment by andyblac** [comment]
are you using the git code ? or code from npm ?, as the code from NPM is not current.

**Comment by soulcook** [comment]
Thanks for the quick reply, Andy. I installed the plugin using the Homebridge Console. which I think pulls it from npm. Will try again using git code...

**Comment by andyblac** [comment]
ye, give the git code a go, it should fix your issue.

**Comment by soulcook** [comment]
wait a minute though... the installation instructions in the readme on git say to install using 

npm install -g homebridge-risco-alarm

Won't this install the npm version again?

**Comment by andyblac** [comment]
yes, just pull the git code [here](https://github.com/szlaskidaniel/homebridge-risco-alarm/archive/master.zip) unzip it, and upload to replace the content in the plugin folder on your install.

**Comment by soulcook** [comment]
ok!

**Comment by andyblac** [comment]
then restart homebridge.

**Comment by soulcook** [comment]
yup. will try now.

**Comment by soulcook** [comment]
It worked! Many thanks.

btw... there's a comma missing in the sample-config (and in the readme version) so it doesn't work as provided... just json syntax. Also I think the riscoSiteId value should be in quotes (string)

**Comment by andyblac** [comment]
glad you got it working.

**Comment by soulcook** [comment]
One more quick question: how do I tell it to do a PART SET? Can’t see a
way.

**Comment by andyblac** [comment]
if you have set the ` "partialCommand": "partially",` in config, in HomeKit long press on Alarm icon and choose `Home`.

**Comment by soulcook** [comment]
Great. Thanks again.

**Comment by andyblac** [comment]
or try `Night` think either work.
