### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by platini76** [szlaskidaniel/homebridge-risco-alarm#26]
[2020-6-19 3:54:14] Plugin 'homebridge-risco-alarm-fork' tried to register with an incorrect plugin identifier: 'homebridge-risco-alarm'. Please report this to the developer!
[2020-6-19 3:54:14] Registering accessory 'homebridge-risco-alarm-fork.RiscoAlarm'

**Comment by gawindx** [comment]
the risco-fork plugin is developed by someone other than szlaskidaniel, and szlaskidaniel has stopped maintaining the original plugin.
I personally develloped another plugin supporting more devices based on this same original plugin from szlaskidaniel.
you can find it under the name of « homebridge-risco-platform ».
the principle of configurations is essentially the same.

I know that there are still some bugs (concerning the refresh of the detectors among others and the possibility of defining the detectors as being of another type such as door contacts, etc.) but I am currently working on another project and I will correct this defect as soon as possible.
the npm will be updated at this time so you will normally only have to accept the update to get the corrected version.

I run it under docker with the image of "oznu/homebridge" without any problem
