### ISSUE TITLE
Voice command in italian

### ISSUE THREAD

**Issue by valeandres** [szlaskidaniel/homebridge-risco-alarm#4]
great work on this repository. thank you for sharing.
excuse my ignorance but I use Italian as default Siri language on my phone and I can not seem to get it to "understand" me. if I switch to English it does work perfectly well. Any advice?

**Comment by szlaskidaniel** [comment]
Hi, I'm glad that it works fine for you. According to Siri, I'm sorry but I cannot help here.
It's Apple issue / role here - not homebridge Plugin.
