### ISSUE TITLE
Domoticz Accessory 

### ISSUE THREAD

**Issue by rp1989** [szlaskidaniel/homebridge-risco-alarm#5]
Hi,

Firstly, thank you for this! Works perfectly in homekit. Any ideas how i could make risco cloud work in domoticz? 

Also do you have plans to make other zones working from homekit such as ‘part set’ rather then setting the alarm for whole house?

**Comment by szlaskidaniel** [comment]
It's not planned for now. But possible will be added later.
With help it should support proper reading for Partial Arm for now (1.26v)
