### ISSUE TITLE
how to configure multi partitions

### ISSUE THREAD

**Issue by platini76** [szlaskidaniel/homebridge-risco-alarm#6]
It is not clear how to configure multi partition.

I have 2 partitions and I want to have possibility to activate/deactivate

ALL
PARTITION 1
PARTITION 2

it is possible and how?

**Comment by szlaskidaniel** [comment]
Hi, nope.
When you ARM you ARM what is defined in config. By default ALL.
You can ovverride it by customized string for arm/disarm
like "0:armed 1:armed 2:armed".

Apologies but I do not have access to mulipartition system so this is based on help from other guy (closed issue in this repo)
